### ISSUE TITLE
actor_weapon actor1 tag_weapon_Right cheytac_mp

### ISSUE THREAD

**Issue by hairline01** [cxvl/IW4MVM#3]
i was watching https://www.youtube.com/watch?v=J-ePEX7fhZM and because of the new mod somethings are different. 
like how the anims are already precached and shit
took a while for me to find out about that. 
basically i type in the actor_Weapon command and all that other jazz but nothing happens. 
just wondering if theres a new sort of format for the command.

**Comment by cxvl** [comment]
@hairline01 Since the 2.0 version a camouflage argument has been added to the weapon function.
Now commands should look like : /actor_weapon acotr1 tag_weapon_right cheytac_mp fall
Camo argument is either : **desert, arctic, woodland, digital, urban, red, blue, fall**

Sorry for that late response by the way.
